config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :messages do
  	resources :comments
  end
  root to: "messages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :messages
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of :content
	belongs_to :message
end

app/models/message.rb
class Message < ApplicationRecord
	validates_presence_of :title
	belongs_to :user
	belongs_to :category
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user! , :except=>[:index,:show]
	def create
		@message=Message.find(params[:message_id])

		@comment=@message.comments.build(params.require(:comment).permit(:content))
		@comment.user_id=current_user.id
		@comment.save
		redirect_to message_path(@message)
	end

	def destroy
		@message=Message.find(params[:message_id])
		@comment=@message.comments.find(params[:id])
		
		if @comment.user_id==current_user.id
		  flash[:notice]="刪除成功"
		 @comment.delete
		 redirect_to message_path(@message)

	    end
				
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user! , :except=>[:index,:show]
	before_action :set_message, :only=>[:edit,:update,:destroy]
	
	def index
		@messages=Message.page(params[:page]).per(5)
	end

	def new
		@message=Message.new
	end

	def create
		@message=Message.new(message_params)
        @message.user=current_user
        if @message.save
        	flash[:notice]="更新成功"
            redirect_to message_path(@message)
        else
        	render :action=>:new
        end
	end

	def show
		@message=Message.find(params[:id])
		@comments=@message.comments.page(params[:page]).per(5)
		@comment=Comment.new
	end

	def edit
		@message=current_user.messages.find_by_id(params[:id])
		unless @message.user==current_user
			flash[:notice]="you are not allowed"
			redirect_to messages_path
			return
		end
	end

	def update
		if @message.update(message_params)
			flash[:notice]="更新成功"
		redirect_to message_path(@message)
        else
        	render :action=>:edit
        end
	end

	def destroy
		
		@message.delete
		redirect_to messages_path
	end

	private
	def message_params
		params.require(:message).permit(:title,:content,:category_id)
	end

	def set_message
		@message=current_user.messages.find_by_id(params[:id])
		unless @message
			flash[:notice]="you are not allowed"
			redirect_to messages_path
			return
		end
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MidTerm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/messages/edit.html.erb
<% if @message.errors.any? %>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>


<%= form_for @message, :url=>message_path do |f| %>
	<%= f.label :category %>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/messages/index.html.erb
<h1> 災情支援網</h1>

<ul>
<% @messages.each do |m|%>	
	<li>
	<%= m.title %>
	<%= m.created_at %>
	<%=link_to "show",message_path(m) %>
	<%=link_to "edit",edit_message_path(m) if current_user==m.user %>
	<%=link_to "delete",message_path(m),:method=>"delete" if current_user==m.user%>
	</li>
<% end %>
</ul>


<%=link_to "new",new_message_path %>

<%= paginate @messages %>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
    <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>


<%= form_for @message, :url=>messages_path do |f| %>
	<%= f.label :category %>
	<%= f.collection_select(:category_id, Category.all, :id, :name) %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>

app/views/messages/show.html.erb
<ul>

<li><%= @message.category.name %></li>
<li><%= @message.title %></li>
<li><%= @message.content %></li>
<li><%= @message.created_at %></li>
</ul>

<h3>comments</h3>
<ul>
<% @comments.each do |c|%>	
	<li>
	<%= c.content %>
	<%=link_to "delete",message_comment_path(@message,c),:method=>"delete" if current_user.id==c.user_id %>
	</li>
<% end %>
</ul>


<%= form_for @comment, :url=>message_comments_path(@message) do |f| %>

	<%= f.label :content %>
	<%= f.text_area :content %>
	<%= f.submit %>
<% end %>
<%= paginate @comments %>

<%=link_to "home",messages_path %>